export const COMMON_WORDS = [
  "Action", "Agency", "Ancient", "Answer", "Apples", "Arctic", "Armor", "Aspect", "Atomic", "Autumn",
  "Beacon", "Beyond", "Binary", "Bionic", "Breeze", "Bridge", "Bright", "Broken", "Bronze", "Bubble",
  "Camera", "Canvas", "Castle", "Center", "Chaos", "Chrome", "Circle", "Cipher", "Clinic", "Cloud",
  "Cobalt", "Coffee", "Column", "Combat", "Common", "Copper", "Cosmos", "Craft", "Crater", "Crisis",
  "Crystal", "Custom", "Cyber", "Cycle", "Danger", "Dancer", "Desert", "Design", "Device", "Diamond",
  "Digital", "Direct", "Distant", "Doctor", "Dragon", "Dream", "Driver", "Eagle", "Earth", "Effect",
  "Eight", "Elastic", "Elder", "Electric", "Elegant", "Element", "Energy", "Engine", "Enigma", "Escape",
  "Essence", "Ethics", "Ethnic", "Everest", "Exotic", "Expert", "Fabric", "Factor", "Falcon", "Family",
  "Famous", "Fantasy", "Farmer", "Faster", "Feather", "Feature", "Fiber", "Field", "Fierce", "Final",
  "Finger", "Flight", "Flower", "Fluid", "Focus", "Forest", "Formal", "Fortune", "Forward", "Fragile",
  "Frame", "Freedom", "Freeze", "Friend", "Front", "Frozen", "Future", "Galaxy", "Garden", "Gateway",
  "Genius", "Gentle", "Ghost", "Giant", "Glance", "Glass", "Global", "Glory", "Gothic", "Grand",
  "Grants", "Graphic", "Gravity", "Green", "Ground", "Growth", "Guard", "Guest", "Guide", "Guitar",
  "Habit", "Hammer", "Handle", "Harbor", "Hazard", "Health", "Heart", "Heaven", "Heavy", "Helmet",
  "History", "Hockey", "Hollow", "Honest", "Horizon", "Horror", "Hotel", "Human", "Hunter", "Hybrid",
  "Hyper", "Iconic", "Ideal", "Identity", "Impact", "Import", "Index", "Indigo", "Indoor", "Infinite",
  "Initial", "Insects", "Insight", "Instant", "Intense", "Island", "Ivory", "Jacket", "Jaguar", "Jersey",
  "Jewel", "Journal", "Journey", "Judge", "Junior", "Jupiter", "Justice", "Karma", "Kettle", "Keyboard",
  "Kingdom", "Knight", "Labels", "Laptop", "Laser", "Latest", "Layer", "Leader", "Legend", "Lemon",
  "Length", "Lesser", "Letter", "Level", "Liberty", "Library", "Light", "Limits", "Linear", "Liquid",
  "Listen", "Little", "Living", "Local", "Logic", "London", "Lonely", "Legend", "Lunar", "Luxury",
  "Magic", "Magnet", "Mainly", "Major", "Mammal", "Manage", "Mansion", "Manual", "Marble", "Marine",
  "Market", "Matrix", "Matter", "Maximum", "Medical", "Medium", "Melody", "Member", "Memory", "Mental",
  "Mercy", "Message", "Metal", "Method", "Metric", "Micro", "Middle", "Might", "Miller", "Million",
  "Mineral", "Mirror", "Mobile", "Modern", "Modest", "Module", "Moment", "Monitor", "Monkey", "Monster",
  "Morning", "Motion", "Mountain", "Museum", "Music", "Native", "Nature", "Nebula", "Neon", "Network",
  "Neutral", "Night", "Noble", "Normal", "Notice", "Novel", "Nuclear", "Number", "Object", "Ocean",
  "Office", "Online", "Optical", "Option", "Orange", "Orbit", "Order", "Origin", "Output", "Oxygen",
  "Packet", "Palace", "Panel", "Paper", "Parade", "Parent", "Particle", "Passive", "Pattern", "Peace",
  "Penalty", "People", "Perfect", "Period", "Phantom", "Phase", "Phoenix", "Phone", "Photo", "Physics",
  "Piano", "Picture", "Pilot", "Planet", "Plastic", "Platinum", "Player", "Pleasure", "Poetry", "Point",
  "Police", "Policy", "Portal", "Poster", "Power", "Precise", "Premium", "Presence", "Price", "Primary",
  "Prince", "Prison", "Private", "Problem", "Process", "Produce", "Product", "Profile", "Program",
  "Project", "Promise", "Proper", "Protein", "Proton", "Public", "Pulse", "Quality", "Quantum", "Quarter",
  "Quartz", "Queen", "Quickly", "Quiet", "Rabbit", "Radar", "Radiant", "Radical", "Radio", "Railway",
  "Random", "Rapid", "Ratio", "Razor", "Reality", "Reason", "Receipt", "Record", "Reduce", "Reflect",
  "Region", "Regular", "Remote", "Repair", "Report", "Rescue", "Research", "Reserve", "Reset", "Resort",
  "Result", "Return", "Review", "Rhythm", "Ribbon", "Richly", "River", "Robot", "Rocket", "Rough",
  "Route", "Royal", "Rubber", "Rugby", "Safety", "Sailor", "Salary", "Sample", "Sandwich", "Saturn",
  "Savage", "Scanner", "Scene", "Science", "Scope", "Screen", "Script", "Search", "Season", "Second",
  "Secret", "Section", "Sector", "Secure", "Sensor", "Series", "Server", "Service", "Session", "Shadow",
  "Shield", "Shift", "Signal", "Silver", "Simple", "Single", "Sketch", "Skill", "Skinny", "Skylight",
  "Sleep", "Slide", "Slowly", "Small", "Smart", "Smooth", "Social", "Socket", "Sodium", "Solar",
  "Solid", "Source", "Space", "Spark", "Special", "Speech", "Speed", "Sphere", "Spirit", "Splash",
  "Sports", "Spring", "Square", "Stable", "Stage", "Stair", "Standard", "Static", "Station", "Status",
  "Steam", "Steel", "Stellar", "Stereo", "Stone", "Store", "Storm", "Stream", "Street", "Strong",
  "Studio", "Subject", "Subtle", "Success", "Sugar", "Summer", "Summit", "Sunday", "Sunset", "Super",
  "Supply", "Support", "Surface", "Surge", "Survey", "System", "Tablet", "Target", "Teacher", "Techno",
  "Temple", "Tennis", "Tension", "Terminal", "Theory", "Thermal", "Thesis", "Third", "Thread", "Ticket",
  "Tiger", "Timber", "Title", "Today", "Token", "Topic", "Total", "Touch", "Tower", "Track",
  "Trade", "Traffic", "Tragedy", "Travel", "Treasure", "Trends", "Trial", "Tribal", "Triple", "Trophy",
  "Tropical", "Trust", "Truth", "Tunnel", "Twelve", "Twenty", "Typical", "Ultra", "Uniform", "Unique",
  "Unit", "Unity", "Universal", "Unknown", "Update", "Uphill", "Urban", "Urgent", "Utility", "Valley",
  "Value", "Vector", "Vehicle", "Velvet", "Vendor", "Venture", "Verdict", "Version", "Vertex", "Vessel",
  "Veteran", "Victory", "Video", "Viewer", "Village", "Vintage", "Virtual", "Vision", "Visual", "Vital",
  "Voice", "Volume", "Vortex", "Waiter", "Walker", "Walnut", "Warning", "Warrior", "Weather", "Website",
  "Wedding", "Weekly", "Weight", "Welcome", "Welfare", "Western", "Whisper", "Winner", "Winter", "Wisdom",
  "Wizard", "Wonder", "Wooden", "Worker", "World", "Writer", "Yellow", "Younger", "Zenith", "Zodiac", "Zones"
];

export const SPECIAL_SYMBOLS = "!@#$%^&*()_+-=[]{}|;:,.<>?".split("");
